export const LANGUAGE_OPTIONS = [
  { code: "en", label: "English" },
  { code: "kn", label: "ಕನ್ನಡ" },
  { code: "tcy", label: "ತುಳು" },
  { code: "be", label: "Beary" },
];

export const TEXTS = {
  en: {
    brand: "BusConnect",
    tagline: "Scan. Know. Pay. Travel.",
    searchRoute: "Search a Route",
    scanQr: "Scan QR Code",
    routeSearch: "Route Search",
    busDetail: "Bus Detail",
    operator: "Operator",
    admin: "Admin",
    currentStop: "Current stop",
    payNow: "Pay via UPI",
    complaint: "Complaint / Feedback",
    liveStatus: "Live crowd status",
  },
  kn: {
    brand: "ಬಸ್ ಕನೆಕ್ಟ್",
    tagline: "ಸ್ಕ್ಯಾನ್ ಮಾಡಿ. ತಿಳಿದುಕೊಳ್ಳಿ. ಪಾವತಿ ಮಾಡಿ. ಪ್ರಯಾಣಿಸಿ.",
    searchRoute: "ಮಾರ್ಗ ಹುಡುಕಿ",
    scanQr: "QR ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    routeSearch: "ಮಾರ್ಗ ಹುಡುಕಾಟ",
    busDetail: "ಬಸ್ ವಿವರ",
    operator: "ಆಪರೇಟರ್",
    admin: "ಅಡ್ಮಿನ್",
    currentStop: "ಪ್ರಸ್ತುತ ನಿಲ್ದಾಣ",
    payNow: "UPI ಮೂಲಕ ಪಾವತಿ",
    complaint: "ದೂರು / ಪ್ರತಿಕ್ರಿಯೆ",
    liveStatus: "ಲೈವ್ ಸ್ಥಿತಿ",
  },
  tcy: {
    brand: "ಬಸ್‌ಕನೆಕ್ಟ್",
    tagline: "ಸ್ಕ್ಯಾನ್ ಮಲ್ಪುಲೆ. ತೆರಿಪುಲೆ. ಪೇ ಮಲ್ಪುಲೆ. ಪ್ರಯಾಣ ಮಲ್ಪುಲೆ.",
    searchRoute: "ರೂಟ್ ಕೊರ್‍ಲೆ",
    scanQr: "QR ಸ್ಕ್ಯಾನ್ ಮಲ್ಪುಲೆ",
    routeSearch: "ರೂಟ್ ಸರ್ಚ್",
    busDetail: "ಬಸ್ ಡೀಟೈಲ್",
    operator: "ಆಪರೇಟರ್",
    admin: "ಅಡ್ಮಿನ್",
    currentStop: "ಇಪ್ಪುನ ಸ್ಟಾಪ್",
    payNow: "UPI ದಾರಿತ ಪೇ ಮಲ್ಪುಲೆ",
    complaint: "ಕಂಪ್ಲೇಂಟ್ / ಫೀಡ್‌ಬ್ಯಾಕ್",
    liveStatus: "ಲೈವ್ ಸ್ಟೇಟಸ್",
  },
  be: {
    brand: "BusConnect",
    tagline: "Scan maadi. Info nodi. Pay maadi. Travel maadi.",
    searchRoute: "Route search",
    scanQr: "QR scan",
    routeSearch: "Route search",
    busDetail: "Bus detail",
    operator: "Operator",
    admin: "Admin",
    currentStop: "Current stop",
    payNow: "UPI pay",
    complaint: "Complaint / Feedback",
    liveStatus: "Live status",
  },
};

export const t = (lang, key) => TEXTS?.[lang]?.[key] || TEXTS.en[key] || key;
